<?php

function npbs_api_menu(){
    $items = array();
    $items['npbs_apis/test'] = array(
        'title' => 'Test',
        'description' => 'Test',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('npbs_api_main_form'),
        'file' => 'resources/fields_resources.inc',
        'access callback' => TRUE,
    );
    $items['admin/config/custom/npbs_api'] = array(
        'title' => 'Sample API',
        'description' => 'Configure npbs_api module',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('npbs_api_config_form'),
        'access arguments' => array('administer site configuration'),   
        'file' => 'npbs_api.admin.inc',
      );

    return $items;
}

function npbs_api_services_resources_alter(&$resources, &$endpoint){
    //TODO need to set access callback
    $temp_resources = array('node','taxonomy_term', 'taxonomy_vocabulary');
    foreach($temp_resources as $temp_resource){
        $resources[$temp_resource]['operations']['retrieve']['file']['module'] = 'npbs_api';
        $resources[$temp_resource]['operations']['retrieve']['file']['name'] = 'resources/structure_resources';
        $resources[$temp_resource]['operations']['retrieve']['callback'] = '_npbs_api_' . $temp_resource . '_retrieve';

        $resources[$temp_resource]['operations']['create']['file']['module'] = 'npbs_api';
        $resources[$temp_resource]['operations']['create']['file']['name'] = 'resources/structure_resources';
        $resources[$temp_resource]['operations']['create']['callback'] = '_npbs_api_' . $temp_resource . '_create';
    }
}